FROM node:lts-bullseye

# WORKDIR /workspace 
# Create and change to the app directory.
WORKDIR /app

RUN npm install -g pm2
RUN pm2 install pm2-logrotate
RUN apt-get update
RUN apt-get install -y g++ make python3-pip redis

COPY . .

RUN yarn install
RUN yarn build


CMD ["yarn", "start"]